### PR TITLE
[MartTools] Fix performance issues.

### LINKED ISSUE #50: [MartTools] Blocking bot loop because of SQL stuff

### PR DESCRIPTION
**Pull request by PredaaA**
- Add an internal cache.
- Use of that cache on listeners and commands.
- That cache is dumped with new values to the DB every 5 minutes, and at unloads.
- No longer storing guild IDs. It includes a migration tool launched automatically on load if it's an old DB.

All this will help bots that were having a very hard time with this cog, because of writes on all events to the DB.

Closes #50.

### CODE REVIEW

**Comment by PredaaA** [comment]
# If someone's interested to test it:

First __**please make a save of your old MartTools.db**__ that is located in your cogs data path.
When loading the new cog it will delete the old tables with your values and migrate them to a new table.
Then:
- `cog uninstall martools`
- `repo add tmp https://github.com/PredaaA/predacogs/tree/martools-caching`
- `cog install tmp martools`
- `load martools`

Let it loaded for a few days, and let me know if there's any error.

**Comment by PredaaA** [comment]
- [ ] Fix unload not always saving all the data to the DB.

**Review by PredaaA — COMMENTED** [review]
It's been tested for now a few weeks on two bots without issues. There is now no longer any blocking with that cog finally.

**Comment by kablekompany** [comment]
Preda POG

**Comment by NeuroAssassin** [comment]
Preda EXTRA POG

**Comment by maxbooiii** [comment]
Preda MEGA POG

**Comment by Predeactor** [comment]
Preda EXTRA MEGA POG

**Pull request merged**
